"""initial migration

Revision ID: 587bf427336d
Revises: 
Create Date: 2021-10-07 22:19:28.250496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587bf427336d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('server_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Text(), nullable=False),
    sa.Column('chat', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('server_id')
    )
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_server_guild_id'), ['guild_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_server_guild_id'))

    op.drop_table('server')
    # ### end Alembic commands ###
