name: deploy to aws
on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: self-hosted
        
    strategy: 
      matrix:
        node-version: [10.x]
            
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: Restart bot
        run: |
          pm2 stop milho
          pm2 start milho
          python -m alembic upgrade head
